server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/ordenes
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  group:
    aws: ordenes-log-group
